// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"github.com/google/uuid"
)

type Event struct {
	EventID   uuid.UUID      `json:"eventID"`
	UserID    uuid.UUID      `json:"userID"`
	Timestamp time.Time      `json:"timestamp"`
	EventType string         `json:"eventType"`
	Metadata  map[string]any `json:"metadata"`
}

type EventCount struct {
	EventType string `json:"eventType"`
	Count     int32  `json:"count"`
}

type Mutation struct {
}

type NewEvent struct {
	UserID    uuid.UUID      `json:"userID"`
	EventType string         `json:"eventType"`
	Metadata  map[string]any `json:"metadata"`
}

type Query struct {
}
