// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/h22k/analyzify/ent/event"
	"github.com/h22k/analyzify/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	eventFields := schema.Event{}.Fields()
	_ = eventFields
	// eventDescEventType is the schema descriptor for eventType field.
	eventDescEventType := eventFields[2].Descriptor()
	// event.EventTypeValidator is a validator for the "eventType" field. It is called by the builders before save.
	event.EventTypeValidator = eventDescEventType.Validators[0].(func(string) error)
	// eventDescTimestamp is the schema descriptor for timestamp field.
	eventDescTimestamp := eventFields[3].Descriptor()
	// event.DefaultTimestamp holds the default value on creation for the timestamp field.
	event.DefaultTimestamp = eventDescTimestamp.Default.(func() time.Time)
	// eventDescID is the schema descriptor for id field.
	eventDescID := eventFields[0].Descriptor()
	// event.DefaultID holds the default value on creation for the id field.
	event.DefaultID = eventDescID.Default.(func() uuid.UUID)
}
